from . import db

class TrResultado(db.Model):
    __tablename__ = 'Tr_Resultado'

    Tr_ResultadoID          = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    Tr_ResultadoAno         = db.Column(db.SmallInteger, nullable=False)
    Tr_ResultadoMes         = db.Column(db.String(20),   nullable=False)
    Tr_ResultadoConta       = db.Column(db.String(120),  nullable=False)
    Tr_ResultadoOrcado      = db.Column(db.Float,        nullable=True)
    Tr_ResultadoRealizado   = db.Column(db.Float,        nullable=True)
    Tr_ResultadoRealAntxAtu = db.Column(db.Float,        nullable=True)
    Tr_ResultadoRealxOrc    = db.Column(db.Float,        nullable=True)
    Tr_ResultadoAnoAnterior = db.Column(db.Float,        nullable=True)


class TrBalancete(db.Model):
    __tablename__ = 'Tr_Balancete'

    Tr_BalanceteId         = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    Tr_BalanceteConta      = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteBacen      = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteTitulo     = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteSaldoAn    = db.Column(db.Numeric(14,2), nullable=False)
    Tr_BalanceteSaldoAt    = db.Column(db.Numeric(14,2), nullable=False)
    Tr_BalanceteDebito     = db.Column(db.Numeric(14,2), nullable=False)
    Tr_BalanceteCredito    = db.Column(db.Numeric(14,2), nullable=False)
    Tr_BalanceteNCredito   = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteNDebito    = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteSate90     = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteSapos90    = db.Column(db.String(200),  nullable=False)
    Tr_BalanceteTituloRel  = db.Column(db.String(200), nullable=False)
    Tr_BalanceteMesAno     = db.Column(db.String(7),   nullable=False)
    Tr_BalanceteCentroCusto= db.Column(db.String(200))


class TrEmpandamento(db.Model):
    __tablename__ = 'Tr_Empandamento'

    Tr_EmpandamentoID           = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    Tr_EmpandamentoAno          = db.Column(db.SmallInteger, nullable=False)
    Tr_EmpandamentoMes          = db.Column(db.String(20), nullable=False)
    Tr_EmpandamentoDataBase     = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoContrato     = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoCodTaxa      = db.Column(db.String(10), nullable=True)
    Tr_EmpandamentoConta        = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoCodLF        = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoDtEmissao    = db.Column(db.Date, nullable=True)
    Tr_EmpandamentoNumParc      = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoParcGer      = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoVencFim      = db.Column(db.Date, nullable=True)
    Tr_EmpandamentoPgtoFim      = db.Column(db.Date, nullable=True)
    Tr_EmpandamentoSaldo        = db.Column(db.Numeric(14,2), nullable=True)
    Tr_EmpandamentoRestantes    = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoSituacao     = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoNivelRisco   = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoDiaFixo      = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoValor        = db.Column(db.Numeric(14,2), nullable=True)
    Tr_EmpandamentoTipoVenc     = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoDiaBase      = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoMatSet       = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoIdGpsol      = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoIdOpGpsol    = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoValorContabil = db.Column(db.Numeric(14,2), nullable=True)
    Tr_EmpandamentoNome         = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoCodUnid      = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoSit          = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoNomeUnid     = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoCodCart      = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoCodSet       = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoVencIni      = db.Column(db.Date, nullable=True)
    Tr_EmpandamentoNomeTaxa     = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoNomeLF       = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoJuros        = db.Column(db.Numeric(14,2), nullable=True)
    Tr_EmpandamentoNomeCart     = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoRaa          = db.Column(db.Numeric(14,2), nullable=True)
    Tr_EmpandamentoCidade       = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoCodCid       = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoSaldoAtual   = db.Column(db.Numeric(14,2), nullable=True)
    Tr_EmpandamentoCicloCliente = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoNomeAgente   = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoCodCnae      = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoCodAgencia   = db.Column(db.SmallInteger, nullable=True)
    Tr_EmpandamentoAgencia      = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoDoc          = db.Column(db.String(20), nullable=True)
    Tr_EmpandamentoCodBanco     = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoBancoC       = db.Column(db.String(120), nullable=True)
    Tr_EmpandamentoAnoMes       = db.Column(db.String(10), nullable=True)


class TrRestituidos(db.Model):
    __tablename__ = 'Tr_Restituidos'

    Tr_RestituidoId          = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    Tr_RestituidoConta       = db.Column(db.String(20),   nullable=False)
    Tr_RestituidoNome        = db.Column(db.String(120),  nullable=False)
    Tr_RestituidoLancamento  = db.Column(db.String(200),  nullable=True)
    Tr_RestituidoData        = db.Column(db.Date,         nullable=True)
    Tr_RestituidoValor       = db.Column(db.Numeric(14,2),nullable=True)
    Tr_RestituidoCodUnid     = db.Column(db.String(20),   nullable=True)


class Tr_Saldos(db.Model):
    __tablename__ = 'Tr_Saldos'

    Tr_SaldosId          = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    Tr_SaldosDataBase    = db.Column(db.SmallInteger, nullable=True)
    Tr_SaldosContrato    = db.Column(db.String(20),    nullable=True)
    Tr_SaldosTaxa     = db.Column(db.String(20),    nullable=True)
    Tr_SaldosConta       = db.Column(db.String(20),    nullable=True)
    Tr_SaldosCodLF       = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosDtEmissao   = db.Column(db.Date,          nullable=True)
    Tr_SaldosNumParc     = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosParcGer     = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosVencFim     = db.Column(db.Date,          nullable=True)
    Tr_SaldosPgtoFim     = db.Column(db.Date,          nullable=True)
    Tr_SaldosSaldo       = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosRestantes   = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosSituacao    = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosNvAtual     = db.Column(db.String(10),    nullable=True)
    Tr_SaldosDiaFixo     = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosValor       = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosTipoVenc    = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosDiaBase     = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosValorContabil = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosNome        = db.Column(db.String(120),   nullable=True)
    Tr_SaldosCodUnid     = db.Column(db.String(20),    nullable=True)
    Tr_SaldosSit         = db.Column(db.String(20),    nullable=True)
    Tr_SaldosNomeUnid    = db.Column(db.String(120),   nullable=True)
    Tr_SaldosCodCart     = db.Column(db.String(20),    nullable=True)
    Tr_SaldosVencIni     = db.Column(db.Date,          nullable=True)
    Tr_SaldosNomeTaxa    = db.Column(db.String(120),   nullable=True)
    Tr_SaldosNomeLF      = db.Column(db.String(120),   nullable=True)
    Tr_SaldosJuros       = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosNomeCart    = db.Column(db.String(120),   nullable=True)
    Tr_SaldosRaa         = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosCidade      = db.Column(db.String(120),   nullable=True)
    Tr_SaldosCodCid      = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosCodAgencia  = db.Column(db.SmallInteger,  nullable=True)
    Tr_SaldosAgencia     = db.Column(db.String(120),   nullable=True)
    Tr_SaldosDoc         = db.Column(db.String(20),    nullable=True)
    Tr_SaldosRaaFuturas  = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosCodBanco    = db.Column(db.String(20),    nullable=True)
    Tr_SaldosNomeSetor   = db.Column(db.String(120),   nullable=True)
    Tr_SaldosIof         = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosProvisao    = db.Column(db.Numeric(14,2), nullable=True)
    Tr_SaldosMatSet      = db.Column(db.String(120),   nullable=True)
    Tr_SaldosCodSet      = db.Column(db.String(20),    nullable=True)
    Tr_SaldosAnoMes      = db.Column(db.String(10),    nullable=True)